### ISSUE TITLE
Logging of subscriptions and unsubscriptions and crash in case of invalid xml

### ISSUE THREAD

**Issue by Raknison123** [ParticularLabs/NServiceBus.FileBasedRouting#20]
Could you please add some (more) logging for new subscriptions and unsubscriptions in case of any changes in routingFile.xml or even on Startup of the service?
If you modify the routingFile.xml to invalid XML NServiceBus.Host.exe crashes hard.
Is it possible to just keep the last valid routing configuration in memory and log an exception instead of crashing?

**Comment by timbussmann** [comment]
Hey @Raknison123 
> If you modify the routingFile.xml to invalid XML NServiceBus.Host.exe crashes hard.

this shouldn't be the case. This is how the endpoint should behave:
* If you start your endpoint with an invalid XML, it will fail to start (and crash)
* If you modify the XML after an initial, successful file load, it will log an error but continue to use the previously read file.
In case this isn't what you're seeing, can you describe the steps to reproduce that behavior or can you share a repro sample with us?

regarding the logging: What kind of information would you be interested in?

**Comment by HEskandari** [comment]
@Raknison123 As Tim said, the last configuration is still valid if you put in an invalid routing configuration file. We have made further changes so in the case of a typo in the routing file (e.g. a typo in one of the message types) it would only log a WARN and wouldn't crash the endpoint. Obviously in this case, since the routing file is partially valid, it will still overwrite the old one and become effective.

Does this address your concerns? If not, could you elaborate what exactly you are expecting?

**Comment by timbussmann** [comment]
Hey @Raknison123 as we haven't heard back from you anymore, we're going to close this issue for now. Please check out the soon the be released version 1.2 which contains a few changes described by @HEskandari.

**Comment by Raknison123** [comment]
Hey @timbussmann sorry for the delayed answer.
According to the above mentioned service crash, this happens in case if you modify the routing.xml file to an INVALID xml.
This will throw the Exception("The configured routing file is no valid XML file.", e); in XmlRoutingFileAccess.cs, line 24. This is probably supposed to be like that?
P.S: I will extend the FileBasedRouting project with a DatabaseBasedRoutingFeature because I want to store the routing configuration in a SQLServer database table.
Should I share my implementation with you guys? It might not be that generic as it should for your demands. It will only support SQLServer database.

**Comment by timbussmann** [comment]
hey @Raknison123 
thanks for getting back to us. You're right, it seems like a failure in parsing the file does indeed crash the process. That's not intentional as after startup, failures to read the file should be logged as a warning and the previous file should be used. I'll have a closer look into that.

regarding your database based routing storage, it's something we definitely were think about as well but haven't come around to follow through yet. Of course we would be interested in seeing your approach, so feel free share it with us 👍

**Comment by timbussmann** [comment]
I raised a dedicated issue to track the issue @Raknison123, please see #27
