### ISSUE TITLE
Unable to send subscription messages to non-FBR endpoint

### ISSUE THREAD

**Issue by dvdstelt** [ParticularLabs/NServiceBus.FileBasedRouting#32]
### Problem description

When a single endpoint, for whatever reason, does not participate in FileBasedRouting like others, it is impossible to subscribe to messages do to [this terminator](https://github.com/ParticularLabs/NServiceBus.FileBasedRouting/blob/develop/src/NServiceBus.FileBasedRouting/SubscribeTerminator.cs). If a user would like to subscribe to such an endpoint, the only thing could be to manually create a subscription message or put the subscription in the subscription storage manually.

Would it be an option to disable the behavior or bypass it in any other way?

**Comment by SzymonPobiega** [comment]
Because the whole purpose of FBR is to not need to subscribe or unsubscribe we initially decided to disable it and log `warn`. This prevents integration with classic endpoints.

In order to allow this we could stop overriding the terminators. This would cause the subscribe messages be sent if the publisher is registered via `RegisterPublisher`.

I propose we:
 * Introduce explicit API to enable MDPS like `EnableMessageDrivenPubSub()`
 * Override the terminators only if MDPS is disabled (default)

**Comment by MSWCRB** [comment]
Hi - just to add to the conversation.  The use case is that we would like to use FileBasedRouting for the endpoints in the service we are writing, but our service does need to listen to a few events coming from other external services, and we can't control whether they use file based routing or not.  In such a scenario currently, it means we cannot use file based routing.  

I am working with @dvdstelt on a proposed PR to solve.

**Comment by timbussmann** [comment]
With #35 being merged, I think we can close this. Release 2.1 will contain the API to re-enable message driven subscriptions if needed.
